import React from "react";
import { fmtRp, fmtTime } from "../utils/format";

/**
 * Renders the API response. The backend returns the itinerary fields plus
 * a server-generated `story` block of shape { story, vibe } — a single
 * flowing paragraph (no markdown, no bullets) generated by the LLM.
 *
 * Robustness:
 *   - Empty steps[] → render aksi-able empty state with reason from backend.
 *   - notices[]     → surface as info banner above timeline.
 *   - distance/budget violations are detected client-side as a defense check.
 */

// Haversine for client-side distance verification (matches backend).
function haversineKm(a, b) {
  const R = 6371.0;
  const lat1 = (a.lat * Math.PI) / 180;
  const lat2 = (b.lat * Math.PI) / 180;
  const dLat = ((b.lat - a.lat) * Math.PI) / 180;
  const dLng = ((b.lng - a.lng) * Math.PI) / 180;
  const s =
    Math.sin(dLat / 2) ** 2 +
    Math.cos(lat1) * Math.cos(lat2) * Math.sin(dLng / 2) ** 2;
  return 2 * R * Math.asin(Math.sqrt(s));
}

export default function ResultsScreen({ params, result, onRestart, onEditParams }) {
  const itin = result || {};
  const steps = Array.isArray(itin.steps) ? itin.steps : [];
  const story = (result && result.story) || { story: "", vibe: "" };
  const notices = Array.isArray(itin.notices) ? itin.notices : [];

  // ─── Empty state: tidak ada destinasi yang lolos constraint ───────
  if (steps.length === 0) {
    // Build empty-state copy: prefer backend notices (specific reasons)
    // over generic tips.
    const backendReasons = notices.length > 0;

    return (
      <div className="results rise">
        <div className="empty-state">
          <div className="empty-icon" aria-hidden="true">🗺️</div>
          <h2>Belum ada destinasi yang cocok</h2>

          {backendReasons ? (
            <div className="empty-notices">
              {notices.map((n, i) => (
                <div key={i} className="empty-notice-row">
                  <span className="bullet">•</span>
                  <span>{n}</span>
                </div>
              ))}
            </div>
          ) : (
            <p>
              Constraint yang kamu pilih agak ketat sehingga agen tidak bisa menemukan destinasi
              yang memenuhi semuanya. Coba tweak parameternya:
            </p>
          )}

          <ul className="empty-tips">
            {params.maxKm != null && (
              <li>
                Naikkan <strong>jarak maks dari home</strong> ({params.maxKm} km saat ini) — coba
                jadi 25-40 km untuk Bandung Raya.
              </li>
            )}
            {params.budget != null && (
              <li>
                Naikkan <strong>budget</strong> ({fmtRp(params.budget)} saat ini) — beberapa
                destinasi populer bertarif &gt;Rp 50.000.
              </li>
            )}
            {params.endMin - params.startMin < 360 && (
              <li>
                Tambah <strong>durasi perjalanan</strong> — minimal 6 jam disarankan untuk{" "}
                {params.count} destinasi.
              </li>
            )}
            <li>
              Pilih kategori yang lebih luas — saat ini:{" "}
              <strong>{params.categories.join(", ") || "semua"}</strong>.
            </li>
          </ul>

          <div className="results-actions" style={{ marginTop: 28, justifyContent: "center" }}>
            <button className="btn primary" onClick={onEditParams}>
              ← Ubah parameter
            </button>
            <button className="btn ghost" onClick={onRestart}>
              ↻ Mulai dari awal
            </button>
          </div>
        </div>
      </div>
    );
  }

  // ─── Normal render ────────────────────────────────────────────────
  const gmaps = (d) =>
    d.gmaps_url ||
    `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(
      (d.name || "") + ", Bandung"
    )}`;

  const cats = [...new Set(steps.map((s) => s.dest.category))];

  // Defensive defaults.
  const totalCost = Number(itin.totalCost || 0);
  const totalKm = Number(itin.totalKm || 0);
  const totalTime = Number(itin.totalTime || 0);
  const returnKm = Number(itin.returnKm || 0);
  const returnMin = Number(itin.returnMin || 0);
  const arriveHome = Number(itin.arriveHome || params.startMin);
  const overBudget = Boolean(itin.overBudget);
  const spareMin = Number(itin.spareMin || 0);

  // Client-side validation: check for any destination violating max_km
  // (defense in depth — backend should have already filtered these out).
  const distViolations = (() => {
    if (params.maxKm == null) return [];
    return steps
      .map((s) => ({
        name: s.dest.name,
        d: haversineKm(params.home, { lat: s.dest.lat, lng: s.dest.lng }),
      }))
      .filter((x) => x.d > params.maxKm);
  })();

  // User-budget overrun check (different from backend's overBudget which is time-based)
  const overUserBudget =
    params.budget != null && totalCost > Number(params.budget);

  return (
    <div className="results rise">
      <div className="results-header">
        <div>
          <div className="kicker" style={{ marginBottom: 10 }}>
            Itinerary Tersusun
          </div>
          <h2>
            Petualangan <em>{(story.vibe || cats.join(" & ")).toLowerCase()}</em> di Bandung
          </h2>
        </div>
        <div style={{ textAlign: "right" }}>
          <div className="date">
            {new Date().toLocaleDateString("id-ID", {
              weekday: "long",
              day: "numeric",
              month: "long",
            })}
          </div>
          <div style={{ marginTop: 6, color: "var(--ink-mute)", fontSize: 13 }}>
            {steps.length} destinasi · dari {params.homeName}
          </div>
        </div>
      </div>

      {/* Backend notices banner (not error — informational about constraints) */}
      {notices.length > 0 && (
        <div className="result-notices">
          <div className="rn-head">ℹ Catatan dari sistem</div>
          {notices.map((n, i) => (
            <div key={i} className="rn-item">{n}</div>
          ))}
        </div>
      )}

      {/* Distance violations warning (defense in depth) */}
      {distViolations.length > 0 && (
        <div className="result-notices result-notices-warn">
          <div className="rn-head">⚠ Beberapa destinasi melebihi batasan jarak</div>
          {distViolations.map((v, i) => (
            <div key={i} className="rn-item">
              {v.name} — {v.d.toFixed(1)} km dari titik mulai (batas: {params.maxKm} km)
            </div>
          ))}
        </div>
      )}

      {/* Summary cards */}
      <div className="summary-grid">
        <div className="sum-card">
          <div className="lab">Destinasi</div>
          <div className="val">
            {steps.length}
            <small>tempat</small>
          </div>
          <div className="sub">{cats.join(" · ")}</div>
        </div>
        <div className="sum-card">
          <div className="lab">Total Biaya Tiket</div>
          <div className="val">
            {fmtRp(totalCost).replace("Rp ", "")}
            <small>rupiah</small>
          </div>
          <div className="sub">
            {params.budget != null ? (
              overUserBudget ? (
                <span style={{ color: "var(--coral)" }}>
                  ⚠ Lewat budget {fmtRp(totalCost - params.budget)}
                </span>
              ) : (
                `Sisa budget: ${fmtRp(Math.max(0, params.budget - totalCost))}`
              )
            ) : (
              "Tanpa batas budget"
            )}
          </div>
        </div>
        <div className="sum-card">
          <div className="lab">Total Jarak</div>
          <div className="val">
            {totalKm.toFixed(1)}
            <small>km</small>
          </div>
          <div className="sub">Termasuk perjalanan pulang ({returnKm.toFixed(1)} km)</div>
        </div>
        <div className="sum-card">
          <div className="lab">Total Waktu</div>
          <div className="val">
            {Math.floor(totalTime / 60)}
            <small>
              jam {totalTime % 60} mnt
            </small>
          </div>
          <div className="sub">
            {overBudget ? (
              <span style={{ color: "var(--coral)" }}>
                ⚠ Lewat batas {Math.abs(spareMin)} mnt
              </span>
            ) : (
              <span style={{ color: "var(--jade)" }}>
                ✓ Selesai sebelum {fmtTime(arriveHome)}
              </span>
            )}
          </div>
        </div>
      </div>

      {/* Timeline */}
      <div className="section-head">
        <h3>Rute & Detail Itinerary</h3>
        <span className="count">— klik nama tempat untuk buka di Google Maps</span>
      </div>

      <div className="timeline">
        {/* Start row */}
        <div className="tl-row">
          <div className="tl-time">
            <div className="arr">{fmtTime(params.startMin)}</div>
            <div className="dep">Berangkat</div>
          </div>
          <div className="tl-axis">
            <div className="tl-dot start" />
          </div>
          <div className="tl-body">
            <div className="top">
              <div className="name" style={{ color: "var(--ink)" }}>
                {params.homeName}
                <span
                  style={{
                    fontSize: 12,
                    color: "var(--ink-dim)",
                    fontFamily: "var(--font-mono)",
                    marginLeft: 8,
                  }}
                >
                  HOME
                </span>
              </div>
              <span className="meta-pill">Titik Awal</span>
            </div>
            <div className="desc">
              Awali perjalananmu dari sini. Pastikan sudah sarapan dan kendaraan terisi penuh.
            </div>
          </div>
        </div>

        {steps.map((s) => {
          const cat = s.dest.category || "Wisata";
          const catClass = String(cat).toLowerCase();
          // Distance from home — useful for user to verify radius constraint
          const distFromHome = haversineKm(params.home, {
            lat: s.dest.lat,
            lng: s.dest.lng,
          });
          return (
            <div key={s.dest.id} className="tl-row">
              <div className="tl-time">
                <div className="arr">{fmtTime(s.arriveAt)}</div>
                <div className="dep">→ {fmtTime(s.departAt)}</div>
                <div className="travel">
                  +{s.travelMin} mnt · {Number(s.travelKm || 0).toFixed(1)} km
                </div>
              </div>
              <div className="tl-axis">
                <div className="tl-dot" />
              </div>
              <div className="tl-body">
                <div className="top">
                  <a href={gmaps(s.dest)} target="_blank" rel="noopener noreferrer" className="name">
                    {s.dest.name}
                    <span className="ext">↗</span>
                  </a>
                  <span className={`meta-pill ${catClass}`}>
                    <span
                      style={{
                        display: "inline-block",
                        width: 6,
                        height: 6,
                        borderRadius: "50%",
                        background: "currentColor",
                      }}
                    />
                    {cat}
                  </span>
                </div>
                <div className="desc">{s.dest.desc || `Destinasi ${cat} di Bandung`}</div>
                <div className="stats">
                  <div className="stat">
                    <div className="k">Tiba</div>
                    <div className="v">{fmtTime(s.arriveAt)}</div>
                  </div>
                  <div className="stat">
                    <div className="k">Selesai</div>
                    <div className="v">{fmtTime(s.departAt)}</div>
                  </div>
                  <div className="stat">
                    <div className="k">Tiket</div>
                    <div className="v">
                      {Number(s.dest.ticket) === 0 ? "Gratis" : fmtRp(s.dest.ticket)}
                    </div>
                  </div>
                  <div className="stat">
                    <div className="k">Durasi</div>
                    <div className="v">{s.dest.duration} mnt</div>
                  </div>
                  <div className="stat">
                    <div className="k">Jarak dari Home</div>
                    <div className="v">{distFromHome.toFixed(1)} km</div>
                  </div>
                  <div className="stat">
                    <div className="k">Rating</div>
                    <div className="v">★ {Number(s.dest.rating || 0).toFixed(1)}</div>
                  </div>
                </div>
              </div>
            </div>
          );
        })}

        {/* End row */}
        <div className="tl-row">
          <div className="tl-time">
            <div className="arr">{fmtTime(arriveHome)}</div>
            <div className="dep">Kembali</div>
            <div className="travel">
              +{returnMin} mnt · {returnKm.toFixed(1)} km
            </div>
          </div>
          <div className="tl-axis">
            <div className="tl-dot end" />
          </div>
          <div className="tl-body">
            <div className="top">
              <div className="name" style={{ color: "var(--ink)" }}>
                Kembali ke {params.homeName}
              </div>
              <span className="meta-pill">Titik Akhir</span>
            </div>
            <div className="desc">
              Perjalanan selesai. Saatnya istirahat dan unggah foto-foto terbaikmu.
            </div>
          </div>
        </div>
      </div>

      {/* Narrative box — fallback kalau LLM gagal */}
      <div className="narrative">
        <div className="nh">
          <div className="title">Cerita Perjalananmu</div>
          <div className="badge">✦ Generated by LLM</div>
        </div>
        <div className="body">
          {story.story ? (
            <p>{story.story}</p>
          ) : (
            <p style={{ color: "var(--ink-mute)", fontStyle: "italic" }}>
              Narasi sedang tidak tersedia (LLM offline). Itinerary tetap valid — selamat jalan!
            </p>
          )}
        </div>
      </div>

      {/* Resume / breakdown — TOTAL BIAYA disamakan dengan summary card.
          BBM ditampilkan sebagai estimasi terpisah (informasi), bukan dijumlahkan
          ke total agar konsisten dengan card "Total Biaya Tiket" di atas. */}
      <div className="resume">
        <div className="section-head">
          <h3>Resume Itinerary</h3>
          <span className="count">— ringkasan akhir</span>
        </div>

        <div className="resume-grid">
          <div className="resume-card">
            <h4>Rincian Biaya Tiket</h4>
            {steps.map((s, i) => (
              <div className="rline" key={s.dest.id}>
                <span className="k">
                  {String(i + 1).padStart(2, "0")}. {s.dest.name}
                </span>
                <span className="v">
                  {Number(s.dest.ticket) === 0 ? "Gratis" : fmtRp(s.dest.ticket)} ·{" "}
                  {s.dest.duration}m
                </span>
              </div>
            ))}
            <div className="rline total">
              <span>Total Biaya Tiket</span>
              <span className="v">{fmtRp(totalCost)}</span>
            </div>
            <div className="rline">
              <span className="k" style={{ color: "var(--ink-dim)", fontSize: 12 }}>
                Estimasi BBM/transport ({totalKm.toFixed(0)} km × Rp 1.200) — perlu disiapkan terpisah
              </span>
              <span className="v" style={{ color: "var(--ink-dim)", fontSize: 12 }}>
                {fmtRp(Math.round(totalKm * 1200))}
              </span>
            </div>
          </div>

          <div className="resume-card">
            <h4>Checklist Sebelum Berangkat</h4>
            <ul className="tips">
              <li>
                <span className="num">1</span> Cek cuaca pagi hari, terutama jika ada destinasi alam
                (Kawah Putih, Tebing Keraton).
              </li>
              <li>
                <span className="num">2</span> Bawa jaket — suhu Bandung Selatan bisa 16°C di pagi
                hari.
              </li>
              <li>
                <span className="num">3</span> Siapkan e-wallet & cash kecil untuk parkir dan tiket
                masuk.
              </li>
              <li>
                <span className="num">4</span> Save GMaps offline untuk area Lembang / Ciwidey
                (sinyal kadang lemah).
              </li>
              <li>
                <span className="num">5</span> Total estimasi waktu {Math.floor(totalTime / 60)}{" "}
                jam — beri buffer 30 menit untuk hal tak terduga.
              </li>
            </ul>
          </div>
        </div>
      </div>

      <div className="results-actions">
        <button className="btn ghost" onClick={onEditParams}>
          ← Ubah parameter
        </button>
        <button className="btn" onClick={onRestart}>
          ↻ Mulai ulang
        </button>
        <button className="btn primary" onClick={() => alert("Itinerary tersimpan!")}>
          ★ Simpan itinerary
        </button>
      </div>
    </div>
  );
}
